{
 "title": "FastAPI Observability",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": "label_values(up, job)" },
   { "name": "log_keyword", "label": "Log Query" }
  ]
 },
 "panels": [
  {
   "title": "API Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests",
     "type": "stat",
     "description": "Total requests count",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(http_requests_total{job=\"$app_name\", handler!~\"/metrics|none\"})"
      }
     ]
    },
    {
     "title": "API Availability",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{job=\"$app_name\"} > 0",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Requests Count",
     "type": "stat",
     "description": "Total Request counts, grouped by each endpoint",
     "gridPos": { "h": 6, "w": 8, "x": 7, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_requests_total{job=\"$app_name\", handler!~\"/metrics|none\"}",
       "legendFormat": "{{method}} {{handler}}"
      }
     ]
    },
    {
     "title": "Requests Average Duration",
     "type": "bargauge",
     "description": "Time it took for requests to generate a response",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "http_request_duration_seconds_sum{job=\"$app_name\", handler!=\"none\"} / http_request_duration_seconds_count{job=\"$app_name\", handler!=\"none\"}",
       "legendFormat": "{{method}} {{handler}}"
      }
     ]
    },
    {
     "title": "Number of Exceptions",
     "type": "stat",
     "description": "Number of exceptions in the last 5 minutes",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(increase(http_requests_total{job=\"$app_name\",status=\"5xx\"}[5m]))"
      }
     ]
    },
    {
     "title": "Percent of 2xx Requests",
     "type": "graph",
     "description": "Percentage of requests that resulted in 2xx status code",
     "gridPos": { "h": 7, "w": 10, "x": 4, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(handler) (http_requests_total{job=\"$app_name\", status=\"2xx\", handler!~\"/metrics|none\"}) / sum by(handler) (http_requests_total{job=\"$app_name\", handler!~\"/metrics|none\"})",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Percent of 5xx Requests",
     "type": "graph",
     "description": "Percentage of requests that resulted in 5xx status code",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum by(handler) (http_requests_total{job=\"$app_name\", status=\"5xx\", handler!~\"/metrics|none\"}) / sum by(handler) (http_requests_total{job=\"$app_name\", handler!~\"/metrics|none\"})",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "PR 99 Requests Duration",
     "type": "graph",
     "description": "Requests duration in the 99th percentile, using the rates from the last minute",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(.99,sum(rate(http_request_duration_seconds_bucket{job=\"$app_name\", handler!~\"/metrics|none\"}[1m])) by(handler, le))",
       "legendFormat": "{{ handler }}"
      }
     ]
    },
    {
     "title": "Request In Process",
     "type": "graph",
     "description": "Number of requests currently being processed, grouped by endpoints",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "http_requests_inprogress{job=\"$app_name\", handler!~\"/metrics|none\"}",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Request Per Sec",
     "type": "graph",
     "description": "Number of requests per second, grouped by endpoints",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "rate(http_requests_total{job=\"$app_name\", handler!~\"/metrics|none\"}[1m])",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "Log Type Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (level) (rate({compose_service=~\"app\"} | pattern `<date> <time> - <name> - <level> - <host> - \"<message>\" <status>` | level!=\"\" [1m]))",
       "legendFormat": "{{level}}"
      }
     ]
    },
    {
     "title": "Log of All FastAPI App",
     "type": "logs",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 22 },
     "targets": [
      {
       "expr": "{compose_service=~\"app\"} |= \"$log_keyword\""
      }
     ]
    }
   ]
  },
  {
   "title": "Custom Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Model Precision",
     "type": "stat",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      { "expr": "model_metrics_precision" }
     ]
    }
   ]
  }
 ]
}